### ISSUE TITLE
Logo /Icon Proposal

### ISSUE THREAD

**Issue by jaldesign93** [ivan770/PiQture#1]
Hey brade, can we make some logo/icon for you web? :D

**Comment by ivan770** [comment]
Of course, any contribution can help.

**Comment by jaldesign93** [comment]
if the logo is finished I will provide the input link here, thanks for the reply. :)

**Comment by ivan770** [comment]
Good luck!

**Comment by jaldesign93** [comment]
hey bro, this logo is done,
this is my contribution post https://utopian.io/utopian-io/@jaldesign/new-logo-icon-proposal-for-piqture
what do you think I beg you to give honest and open value because I want to explain my contribution to someone :(

**Comment by ivan770** [comment]
WOW, very good job! You can open a PR, so I can add you to contributors.

**Comment by jaldesign93** [comment]
it's an honor for me, what can help in this team?
