### ISSUE TITLE
New PiQture Logo/Icon

### ISSUE THREAD

**Issue by aditfreedom** [ivan770/PiQture#2]
Hi there,
I have a Logo/Icon contribution on your web application, Im sorry if there's no permission first.
This is the link, hope you like it : 
https://utopian.io/utopian-io/@rauljoe/contribution-for-piqture-new-logo
What do you think?

**Comment by ivan770** [comment]
Thanks for creating such a cool logo! It's now available in PiQture, starting from `0d853dbc93a93b224249d625407d8f9e1e041751` commit ([Link](https://github.com/ivan770/PiQture/commit/0d853dbc93a93b224249d625407d8f9e1e041751))

Thanks for participation in PiQture creating!
